name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout master
      uses: actions/checkout@v1
      with:
        submodules: true
    - name: Setup go
      uses: actions/setup-go@v1

    - name: Hugo Deploy GitHub Pages
      uses: charlescossette/hugo-deploy-gh-pages@master
      env:
        HUGO_EXTENDED: true
        HUGO_VERSION: 0.82.1
        TARGET_REPO: charlescossette/charlescossette.github.io
        TOKEN: ${{ secrets.DEPLOYMENT_TOKEN }}
        CNAME: 